server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/leaning?serverTimezone=GMT%2b8
    username: root
    password: 1234
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
files:
  upload:
    path: D:/code/files/


